### ISSUE TITLE
Create a container

### ISSUE THREAD

**Issue by mterhar** [mterhar/libhoneyreceiver#1]

**Comment by mterhar** [comment]
Dockerfile

```Dockerfile
FROM golang:1.23 AS build
ARG  OTEL_VERSION=0.112.0
WORKDIR /app
RUN \
    curl -SsL https://github.com/mterhar/libhoneyreceiver/archive/refs/tags/v0.1.tar.gz | tar -xzC /app/
RUN go install go.opentelemetry.io/collector/cmd/builder@v${OTEL_VERSION}
COPY . .
RUN CGO_ENABLED=0 builder --config=manifest.yaml --output-path=/app
 
FROM cgr.dev/chainguard/static:latest
COPY --from=build /app/otelcol-custom /
# COPY config.yaml /
EXPOSE 4317/tcp 4318/tcp 13133/tcp
 
CMD ["/otelcol-custom", "--config=/config.yaml"]
```

**Comment by mterhar** [comment]
Otel configuration

```yaml
receivers:
  libhoney:
    http:
      endpoint: 0.0.0.0:8088
      traces_url_paths:
        - "/1/events/"
        - "/1/batch/"
      include_metadata: true
    auth_api: https://api.honeycomb.io
    resources:
      service_name: service.name
    scopes:
      library_name: library.name
      library_version: library.version
    attributes:
      trace_id: trace_id
      parent_id: parent_id
      span_id: span_id
      name: name
      error: error
      spankind: span.kind
      durationFields:
        - duration_ms

processors:
  batch:
    metadata_keys: 
      - x-honeycomb-team
    metadata_cardinality_limit: 30

  transform:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - set(attributes["collector.after_refinery"], "${env:HOSTNAME}")

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./output.json
  otlp:
    endpoint: "api.honeycomb.io:443"
    auth:
      authenticator: headers_setter

extensions:
  headers_setter:
    headers:
      - action: upsert
        key: x-honeycomb-team
        from_context: x-honeycomb-team
    
service:
  extensions: 
    - headers_setter
  pipelines:
    traces:
      receivers: [libhoney]
      processors: [transform, batch]
      exporters: [otlp]
  telemetry:
    logs:
      level: info
```
